server:
  port: 8082
spring:
  application:
    name: OrderServices
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Bannu@123
    url: jdbc:mysql://localhost:3306/orderservice?createDatabaseIfNotExist=true
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
   

