server:
  port: 8084
spring:
  application:
    name: recommendationserver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Bannu@123
    url: jdbc:mysql://localhost:3306/recommendationserver?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
