server:
  port: 8086
spring:
  application:
    name: api-gateway-service
    
    
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://OrderServices
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://paymentIntegration
          predicates:
            - Path=/payment/**
        - id: product-service
          uri: lb://productCatalogService
          predicates:
            - Path=/product/**
        - id: recommendation-service
          uri: lb://recommendationserver
          predicates:
            - Path=/recommendation/**
        - id: authentication-service
          uri: lb://UserAuthenticationService
          predicates:
            - Path=/auth/**
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

