server:
  port: 8083
spring:
  application:
    name: paymentIntegration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Bannu@123
    url: jdbc:mysql://localhost:3306/paymentserver?createDatabaseIfNotExist=true
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    
